name: CI

on:
  push:
    branches:
      - main

jobs:
  test-rust:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust Nightly and LLVM Tools
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: llvm-tools-preview

    - name: Setup grcov
      uses: SierraSoftworks/setup-grcov@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version: latest

    - name: Run Tests with Coverage
      run: |
        export RUSTFLAGS="-Zinstrument-coverage"
        cargo test

    - name: Generate coverage report
      run: |
        grcov . --binary-path target/debug/deps/ -s . -t lcov --ignore-not-existing --ignore '../**' --ignore '/*' -o ./lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./lcov.info
